### ISSUE TITLE
missing table in FarmManager.lua

### ISSUE THREAD

**Issue by Patar95** [scfmod/fs19_lua#3]
Hey,

thanks for your great work! That saves a lot of time for me. I'm searching for a table where all the farms of a MP-game are in. I just searched with my script but couldn't find any table in "FarmManager".

Now I looked into your documents and saw you found the following:
```
FarmManager = {
  farms = {},
  debug_hasAskedCreate = false,
  loadedMapData = false,
  farmIdToFarm = false
}
```

Unfortunately, I can't find any of these. FarmManager.farms is nil for me. How did you find them?

regards, thomas

**Comment by yumi-modding** [comment]
Hello,
Generally for these managers you need to use the corresponding global variable to access them: g_farmManager here.

**Comment by Patar95** [comment]
Thank you very much. That's it!
